/* Autogenerated file. Do not edit manually. */

/* tslint:disable */
/* eslint-disable */

/*
  Fuels version: 0.45.0
  Forc version: 0.40.1
  Fuel-Core version: 0.18.1
*/

export { LimitOrderPredicateAbi__factory } from './factories/LimitOrderPredicateAbi__factory';
