/* Autogenerated file. Do not edit manually. */

/* tslint:disable */
/* eslint-disable */

/*
  Fuels version: 0.45.0
  Forc version: 0.40.1
  Fuel-Core version: 0.18.1
*/

export type { ProxyContractAbi } from './ProxyContractAbi';

export { ProxyContractAbi__factory } from './factories/ProxyContractAbi__factory';
