/* Autogenerated file. Do not edit manually. */

/* tslint:disable */
/* eslint-disable */

/*
  Fuels version: 0.45.0
  Forc version: 0.40.1
  Fuel-Core version: 0.18.1
*/

import type {
  BigNumberish,
  BN,
  BytesLike,
  Contract,
  DecodedValue,
  FunctionFragment,
  Interface,
  InvokeFunction,
} from 'fuels';

export type AddressInput = { value: string };
export type AddressOutput = AddressInput;
export type ContractIdInput = { value: string };
export type ContractIdOutput = ContractIdInput;
export type ProxySendFundsToPredicateParamsInput = { predicate_root: AddressInput, asset0: ContractIdInput, asset1: ContractIdInput, maker: AddressInput, min_fulfill_amount0: BigNumberish, price: BigNumberish, asset0_decimals: BigNumberish, asset1_decimals: BigNumberish, price_decimals: BigNumberish };
export type ProxySendFundsToPredicateParamsOutput = { predicate_root: AddressOutput, asset0: ContractIdOutput, asset1: ContractIdOutput, maker: AddressOutput, min_fulfill_amount0: BN, price: BN, asset0_decimals: number, asset1_decimals: number, price_decimals: number };

interface ProxyContractAbiInterface extends Interface {
  functions: {
    send_funds_to_predicate_root: FunctionFragment;
  };

  encodeFunctionData(functionFragment: 'send_funds_to_predicate_root', values: [ProxySendFundsToPredicateParamsInput]): Uint8Array;

  decodeFunctionData(functionFragment: 'send_funds_to_predicate_root', data: BytesLike): DecodedValue;
}

export class ProxyContractAbi extends Contract {
  interface: ProxyContractAbiInterface;
  functions: {
    send_funds_to_predicate_root: InvokeFunction<[params: ProxySendFundsToPredicateParamsInput], void>;
  };
}
