/* Autogenerated file. Do not edit manually. */

/* tslint:disable */
/* eslint-disable */

/*
  Fuels version: 0.45.0
  Forc version: 0.40.1
  Fuel-Core version: 0.18.1
*/

import { Interface, Contract } from "fuels";
import type { Provider, Account, AbstractAddress } from "fuels";
import type { ProxyContractAbi, ProxyContractAbiInterface } from "../ProxyContractAbi";

const _abi = {
  "types": [
    {
      "typeId": 0,
      "type": "()",
      "components": [],
      "typeParameters": null
    },
    {
      "typeId": 1,
      "type": "b256",
      "components": null,
      "typeParameters": null
    },
    {
      "typeId": 2,
      "type": "struct Address",
      "components": [
        {
          "name": "value",
          "type": 1,
          "typeArguments": null
        }
      ],
      "typeParameters": null
    },
    {
      "typeId": 3,
      "type": "struct ContractId",
      "components": [
        {
          "name": "value",
          "type": 1,
          "typeArguments": null
        }
      ],
      "typeParameters": null
    },
    {
      "typeId": 4,
      "type": "struct ProxySendFundsToPredicateParams",
      "components": [
        {
          "name": "predicate_root",
          "type": 2,
          "typeArguments": null
        },
        {
          "name": "asset0",
          "type": 3,
          "typeArguments": null
        },
        {
          "name": "asset1",
          "type": 3,
          "typeArguments": null
        },
        {
          "name": "maker",
          "type": 2,
          "typeArguments": null
        },
        {
          "name": "min_fulfill_amount0",
          "type": 5,
          "typeArguments": null
        },
        {
          "name": "price",
          "type": 5,
          "typeArguments": null
        },
        {
          "name": "asset0_decimals",
          "type": 6,
          "typeArguments": null
        },
        {
          "name": "asset1_decimals",
          "type": 6,
          "typeArguments": null
        },
        {
          "name": "price_decimals",
          "type": 6,
          "typeArguments": null
        }
      ],
      "typeParameters": null
    },
    {
      "typeId": 5,
      "type": "u64",
      "components": null,
      "typeParameters": null
    },
    {
      "typeId": 6,
      "type": "u8",
      "components": null,
      "typeParameters": null
    }
  ],
  "functions": [
    {
      "inputs": [
        {
          "name": "params",
          "type": 4,
          "typeArguments": null
        }
      ],
      "name": "send_funds_to_predicate_root",
      "output": {
        "name": "",
        "type": 0,
        "typeArguments": null
      },
      "attributes": [
        {
          "name": "payable",
          "arguments": []
        }
      ]
    }
  ],
  "loggedTypes": [
    {
      "logId": 0,
      "loggedType": {
        "name": "",
        "type": 4,
        "typeArguments": []
      }
    }
  ],
  "messagesTypes": [],
  "configurables": []
}

export class ProxyContractAbi__factory {
  static readonly abi = _abi
  static createInterface(): ProxyContractAbiInterface {
    return new Interface(_abi) as unknown as ProxyContractAbiInterface
  }
  static connect(
    id: string | AbstractAddress,
    accountOrProvider: Account | Provider
  ): ProxyContractAbi {
    return new Contract(id, _abi, accountOrProvider) as unknown as ProxyContractAbi
  }
}
